### ISSUE TITLE
Issue with build using Jekyll

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/website#1]
```bash
(base) ubuntu@ip-172-31-18-107:~/repos/website$ jekyll build
Traceback (most recent call last):
        15: from /home/ubuntu/gems/bin/jekyll:23:in `<main>'
        14: from /home/ubuntu/gems/bin/jekyll:23:in `load'
        13: from /home/ubuntu/gems/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
        12: from /home/ubuntu/gems/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
        11: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
        10: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/runtime.rb:20:in `setup'
         9: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/runtime.rb:108:in `block in definition_method'
         8: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/definition.rb:226:in `requested_specs'
         7: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/definition.rb:237:in `specs_for'
         6: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/definition.rb:170:in `specs'
         5: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/definition.rb:258:in `resolve'
         4: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/resolver.rb:22:in `resolve'
         3: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/resolver.rb:49:in `start'
         2: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
         1: from /home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/resolver.rb:255:in `each'
/home/ubuntu/gems/gems/bundler-2.0.2/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-seo-tag' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```

and the following didn't seem to fix the issue on `ubuntu`

```bash
(base) ubuntu@ip-172-31-18-107:~/repos/website$ gem 'jekyll-seo-tag'
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command jekyll-seo-tag
```

**Comment by mmcky** [comment]
Ah ha -- `rubygems` doesn't have the sources for the plugins we use. 

Using:

```
gem install jekyll-seo-tag github-pages
```
